-- Database schema for Traeme la comida
-- Generated based on current Supabase project: xnqucppcldvrvgwgucom

-- Drop existing tables if they exist
DROP TABLE IF EXISTS public.usuario CASCADE;
DROP TABLE IF EXISTS public.pago CASCADE;
DROP TABLE IF EXISTS public.seleccion_opcion CASCADE;
DROP TABLE IF EXISTS public.detalle_pedido CASCADE;
DROP TABLE IF EXISTS public.pedido CASCADE;
DROP TABLE IF EXISTS public.opcion CASCADE;
DROP TABLE IF EXISTS public.producto_categoria_opcion CASCADE;
DROP TABLE IF EXISTS public.categoria_opcion CASCADE;
DROP TABLE IF EXISTS public.producto CASCADE;
DROP TABLE IF EXISTS public.categoria_producto CASCADE;
DROP TABLE IF EXISTS public.mesa CASCADE;
DROP TABLE IF EXISTS public.sala CASCADE;
DROP TABLE IF EXISTS public.configuracion_local CASCADE;

-- Drop existing types if they exist
DROP TYPE IF EXISTS public.tipo_mesa CASCADE;
DROP TYPE IF EXISTS public.estado_pedido CASCADE;
DROP TYPE IF EXISTS public.metodo_pago CASCADE;
DROP TYPE IF EXISTS public.rol_usuario CASCADE;
DROP TYPE IF EXISTS public.estado_detalle_pedido CASCADE;

-- Create custom types
CREATE TYPE public.tipo_mesa AS ENUM ('mesa', 'barra');

-- public.estado_pedido
CREATE TYPE public.estado_pedido AS ENUM ('activo', 'recibido', 'listo', 'servido', 'pendiente_cobro', 'cerrado');

CREATE TYPE public.metodo_pago AS ENUM ('Tarjeta', 'Efectivo', 'GooglePay', 'Bizum');
CREATE TYPE public.rol_usuario AS ENUM ('cocina', 'propietario', 'camarero');
CREATE TYPE public.estado_detalle_pedido AS ENUM ('no_servido', 'listo', 'servido', 'pagado');

-- Create tables

-- public.configuracion_local
CREATE TABLE public.configuracion_local (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_local character varying NOT NULL UNIQUE,
    logo_url text,
    color_primario character varying,
    link_resenas_google text
);

-- public.usuario
CREATE TABLE public.usuario (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario character varying NOT NULL UNIQUE,
    password character varying NOT NULL,
    email character varying UNIQUE,
    rol public.rol_usuario DEFAULT 'camarero'::public.rol_usuario NOT NULL
);

-- public.sala
CREATE TABLE public.sala (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying NOT NULL UNIQUE,
    ancho integer DEFAULT 0,
    alto integer DEFAULT 0
);

-- public.mesa
CREATE TABLE public.mesa (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sala integer NOT NULL REFERENCES public.sala(id) ON DELETE CASCADE,
    tipo public.tipo_mesa DEFAULT 'mesa'::public.tipo_mesa NOT NULL,
    numero character varying NOT NULL,
    uuid text UNIQUE,
    pos_x integer DEFAULT 0,
    pos_y integer DEFAULT 0,
    ancho integer DEFAULT 0,
    alto integer DEFAULT 0,
    rotacion integer DEFAULT 0,
    UNIQUE (id_sala, numero)
);



-- public.categoria_producto
CREATE TABLE public.categoria_producto (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying NOT NULL UNIQUE,
    orden integer NOT NULL
);

-- public.producto
CREATE TABLE public.producto (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria_producto integer NOT NULL REFERENCES public.categoria_producto(id) ON DELETE CASCADE,
    nombre character varying NOT NULL UNIQUE,
    descripcion text,
    precio numeric DEFAULT 0.00 NOT NULL,
    imagen_url text,
    disponible boolean DEFAULT true NOT NULL,
    orden integer NOT NULL
);

-- public.categoria_opcion
CREATE TABLE public.categoria_opcion (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying NOT NULL
);

-- public.producto_categoria_opcion
CREATE TABLE public.producto_categoria_opcion (
    id_producto integer NOT NULL REFERENCES public.producto(id) ON DELETE CASCADE,
    id_categoria_opcion integer NOT NULL REFERENCES public.categoria_opcion(id) ON DELETE CASCADE,
    min_selecciones integer DEFAULT 0,
    max_selecciones integer DEFAULT 1,
    orden integer NOT NULL,
    PRIMARY KEY (id_producto, id_categoria_opcion)
);

-- public.opcion
CREATE TABLE public.opcion (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria_opcion integer NOT NULL REFERENCES public.categoria_opcion(id) ON DELETE CASCADE,
    nombre character varying NOT NULL,
    precio_extra numeric DEFAULT 0.00
);

-- public.pedido
CREATE TABLE public.pedido (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mesa integer NOT NULL REFERENCES public.mesa(id) ON DELETE CASCADE,
    es_barra boolean DEFAULT false NOT NULL,
    estado public.estado_pedido DEFAULT 'activo'::public.estado_pedido NOT NULL,
    creado_at timestamp with time zone DEFAULT now() NOT NULL,
    fecha_final timestamp with time zone
);

-- public.detalle_pedido
CREATE TABLE public.detalle_pedido (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido integer NOT NULL REFERENCES public.pedido(id) ON DELETE CASCADE,
    id_producto integer NOT NULL REFERENCES public.producto(id),
    cantidad integer DEFAULT 1 NOT NULL,
    precio_unitario numeric NOT NULL,
    estado public.estado_detalle_pedido DEFAULT 'no_servido'::public.estado_detalle_pedido NOT NULL,
    notas text
);

-- public.seleccion_opcion
CREATE TABLE public.seleccion_opcion (
    id_opcion integer NOT NULL REFERENCES public.opcion(id),
    id_detalle_pedido integer NOT NULL REFERENCES public.detalle_pedido(id) ON DELETE CASCADE,
    precio_extra_aplicado numeric DEFAULT 0.00 NOT NULL,
    PRIMARY KEY (id_opcion, id_detalle_pedido)
);

-- public.pago
CREATE TABLE public.pago (
    id_pedido integer NOT NULL REFERENCES public.pedido(id) ON DELETE CASCADE,
    monto_pagado numeric NOT NULL,
    metodo public.metodo_pago NOT NULL,
    fecha_pago timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (id_pedido)
);
